// HSK Example sentences - English translations
// Maps hanzi -> English translation of the example sentence
const EXAMPLES_EN = {
  // ===== HSK 1 =====
  "爱": "I love you.",
  "八": "I have eight apples.",
  "爸爸": "This is my dad.",
  "杯子": "This cup is pretty.",
  "北京": "I live in Beijing.",
  "本": "I bought a book.",
  "不": "I'm not going.",
  "不客气": "You're welcome, it's nothing.",
  "菜": "This dish is delicious.",
  "茶": "I drink tea.",
  "吃": "Let's eat together.",
  "出租车": "I'm taking a taxi home.",
  "打电话": "I'll call mom.",
  "大": "This house is big.",
  "的": "This is my book.",
  "点": "It's 3 o'clock.",
  "电脑": "I work on a computer.",
  "电视": "I watch TV every day.",
  "电影": "This movie is good.",
  "东西": "I'm going shopping.",
  "都": "We are all students.",
  "读": "I like to read.",
  "对不起": "Sorry, I'm late.",
  "多": "There are a lot of people here.",
  "多少": "How much is this?",
  "儿子": "He is my son.",
  "二": "Two plus two equals four.",
  "饭馆": "Let's eat at the restaurant.",
  "飞机": "I'm flying to Beijing.",
  "分钟": "Please wait five minutes.",
  "高兴": "Nice to meet you.",
  "个": "I have a friend.",
  "工作": "I work at a company.",
  "狗": "I have a dog at home.",
  "汉语": "I'm learning Chinese.",
  "好": "How are you? I'm good.",
  "喝": "I drink water.",
  "和": "I'm going with friends.",
  "很": "It's very hot today.",
  "后面": "The school is behind.",
  "回": "I'm going home now.",
  "会": "I can speak a little Chinese.",
  "火车站": "I'm going to the train station to pick up a friend.",
  "几": "How old are you?",
  "家": "There are four people in my family.",
  "叫": "My name is Xiao Ming.",
  "今天": "Today is Monday.",
  "九": "I start work at 9.",
  "开": "Please open the door.",
  "看": "I'm reading.",
  "看见": "I saw him.",
  "块": "This is 10 yuan.",
  "来": "Please come here a moment.",
  "老师": "Teacher Wang is great.",
  "了": "I ate.",
  "冷": "It's cold today.",
  "里": "The book is in the bag.",
  "零": "It's minus 5 degrees now.",
  "六": "I wake up at 6.",
  "妈妈": "Mom is cooking.",
  "吗": "Are you Chinese?",
  "买": "I'm going to buy apples.",
  "猫": "I have a cat.",
  "没": "I don't have money.",
  "没关系": "It's okay, don't worry.",
  "米饭": "I like to eat rice.",
  "名字": "What's your name?",
  "明天": "See you tomorrow.",
  "哪": "Where are you from?",
  "那": "What's that?",
  "呢": "I'm good, and you?",
  "能": "I can help you.",
  "你": "Hello!",
  "年": "This year is 2026.",
  "女儿": "She is my daughter.",
  "朋友": "He is my best friend.",
  "漂亮": "She is pretty.",
  "苹果": "I eat an apple every day.",
  "七": "A week has seven days.",
  "前面": "The shop is ahead.",
  "钱": "I didn't bring money.",
  "请": "Please sit.",
  "去": "I'm going to school.",
  "热": "The weather is hot today.",
  "人": "There are many people here.",
  "认识": "Nice to meet you.",
  "日": "Today is May 18.",
  "三": "I have three books.",
  "商店": "The shop has already closed.",
  "上": "The book is on the table.",
  "上午": "I have class in the morning.",
  "少": "There are few people here.",
  "什么": "What is this?",
  "十": "I waited 10 minutes.",
  "时候": "When are you coming?",
  "是": "I am a student.",
  "书": "I read every day.",
  "谁": "Who is he?",
  "水": "I want to drink water.",
  "水果": "I like to eat fruit.",
  "睡觉": "I want to sleep.",
  "说话": "Please don't talk.",
  "四": "My family has four people.",
  "岁": "I am 20 years old.",
  "他": "He is a doctor.",
  "她": "She is my teacher.",
  "太": "Great!",
  "天气": "The weather is good today.",
  "听": "I like to listen to music.",
  "同学": "He is my classmate.",
  "喂": "Hello (on the phone).",
  "我": "I am Korean.",
  "我们": "We are friends.",
  "五": "I work 5 days a week.",
  "喜欢": "I like this book.",
  "下": "I'm off work.",
  "下午": "See you in the afternoon.",
  "下雨": "It's raining outside.",
  "先生": "Is Mr. Wang here?",
  "现在": "What time is it now?",
  "想": "I want to drink coffee.",
  "小": "This house is small.",
  "小姐": "Miss, excuse me.",
  "些": "I want some fruit.",
  "写": "Please write your name here.",
  "谢谢": "Thank you for your help.",
  "星期": "There's a meeting on Monday.",
  "学生": "I'm a university student.",
  "学习": "I study Chinese every day.",
  "学校": "My school is big.",
  "一": "I have a question.",
  "衣服": "These clothes are pretty.",
  "医生": "He is a doctor.",
  "医院": "I'm going to the hospital.",
  "椅子": "Please sit on this chair.",
  "有": "I have a younger sister.",
  "月": "It's May now.",
  "再见": "Goodbye, teacher.",
  "在": "I'm at home.",
  "怎么": "What's wrong?",
  "怎么样": "How have you been?",
  "这": "This is my book.",
  "中国": "I want to go to China.",
  "中午": "What's for lunch?",
  "住": "I live in Seoul.",
  "桌子": "The book is on the table.",
  "字": "How do you pronounce this character?",
  "昨天": "I was busy yesterday.",
  "坐": "Please sit here.",
  "做": "I'm cooking.",

  // ===== HSK 2 =====
  "吧": "Let's go.",
  "白": "She's wearing white clothes.",
  "百": "This book is 100 yuan.",
  "帮助": "Thanks for your help.",
  "报纸": "I read the newspaper every day.",
  "比": "He's taller than me.",
  "便宜": "These clothes are cheap.",
  "别": "Don't worry.",
  "唱歌": "She loves singing.",
  "出": "Please go out.",
  "穿": "What should I wear today?",
  "船": "I'm traveling by boat.",
  "次": "I've been to Beijing twice.",
  "从": "I'm from Korea.",
  "错": "You said it wrong.",
  "打篮球": "I like to play basketball.",
  "大家": "Hello everyone.",
  "但是": "I want to go, but I don't have time.",
  "到": "I arrived home.",
  "得": "He runs fast.",
  "弟弟": "I have a younger brother.",
  "第一": "He came in first.",
  "懂": "I understand.",
  "房间": "This room is clean.",
  "非常": "Thank you very much.",
  "服务员": "Waiter, please come here.",
  "高": "He is tall.",
  "告诉": "Please tell me your phone number.",
  "哥哥": "My older brother is a doctor.",
  "给": "Please give me a glass of water.",
  "公共汽车": "I take the bus to work.",
  "公斤": "One kilo of fruit.",
  "公司": "I work at a big company.",
  "贵": "This is too expensive.",
  "还": "I haven't eaten yet.",
  "孩子": "This child is cute.",
  "好吃": "This dish is delicious.",
  "号": "What's the date today?",
  "黑": "It's getting dark.",
  "红": "I like red.",
  "欢迎": "Welcome to China.",
  "回答": "Please answer my question.",
  "机场": "I'm going to the airport to pick up a friend.",
  "鸡蛋": "I ate two eggs.",
  "件": "I bought a piece of clothing.",
  "教室": "The students are in the classroom.",
  "介绍": "Let me introduce.",
  "姐姐": "My older sister is pretty.",
  "近": "My home is close to the company.",
  "进": "Please come in.",
  "就": "I'll be right there.",
  "觉得": "I think this is good.",
  "咖啡": "I drink coffee every day.",
  "开始": "Let's begin class.",
  "考试": "There's a test tomorrow.",
  "可能": "It might rain tomorrow.",
  "可以": "May I come in?",
  "课": "There are three classes today.",
  "快": "You walk too fast.",
  "快乐": "Happy birthday!",
  "累": "I'm tired today.",
  "离": "The school isn't far from here.",
  "两": "I have two children.",
  "路": "This road is long.",
  "旅游": "I like to travel.",
  "卖": "What do you sell here?",
  "慢": "Please speak a little slower.",
  "忙": "I've been busy lately.",
  "每": "I run every day.",
  "妹妹": "My sister is five this year.",
  "门": "Please close the door.",
  "男人": "That man is my father.",
  "您": "Hello, may I ask?",
  "牛奶": "I'm drinking a glass of milk.",
  "女人": "She's a smart woman.",
  "旁边": "He's sitting next to me.",
  "跑步": "I run every morning.",
  "票": "I bought two tickets.",
  "妻子": "His wife is a teacher.",
  "起床": "I get up at 7.",
  "千": "This is 1,000 yuan.",
  "晴": "The weather is clear today.",
  "去年": "Last year I went to China.",
  "让": "Let me see.",
  "上班": "I start work at 9.",
  "身体": "How is your health?",
  "生病": "I was sick yesterday.",
  "生日": "Today is my birthday.",
  "时间": "I don't have time.",
  "事情": "I have a lot to do.",
  "手表": "This watch is expensive.",
  "手机": "My phone is out of battery.",
  "送": "I'll take you home.",
  "所以": "It rained, so I didn't go.",
  "它": "It's my cat.",
  "踢": "They're playing soccer.",
  "题": "This problem is difficult.",
  "跳舞": "She loves to dance.",
  "外": "I'll wait for you outside the door.",
  "完": "I'm done.",
  "玩": "Let's go out and play.",
  "晚上": "See you tonight.",
  "为": "Cheers to you.",
  "问": "I want to ask a question.",
  "问题": "No problem.",
  "希望": "I hope you succeed.",
  "洗": "I'm going to wash my hands.",
  "西瓜": "I love watermelon in summer.",
  "向": "Please go left.",
  "小时": "I waited an hour.",
  "笑": "She laughed happily.",
  "新": "This is my new car.",
  "姓": "My surname is Kim.",
  "休息": "Take a rest.",
  "雪": "It's snowing outside.",
  "颜色": "What color do you like?",
  "眼睛": "Her eyes are big.",
  "羊肉": "I like to eat lamb.",
  "药": "You need to take medicine.",
  "要": "I want a cup of coffee.",
  "也": "I want to go too.",
  "一起": "Let's go together.",
  "已经": "I already ate.",
  "意思": "What does this mean?",
  "因为": "I didn't go out because of rain.",
  "阴": "The weather is cloudy today.",
  "游泳": "I like swimming.",
  "右边": "The bank is on the right.",
  "鱼": "I like to eat fish.",
  "元": "This is 10 yuan.",
  "远": "My home is far from here.",
  "运动": "I exercise every day.",
  "再": "Please say it again.",
  "早上": "Good morning!",
  "张": "Please give me a piece of paper.",
  "长": "This road is long.",
  "丈夫": "Her husband is a teacher.",
  "找": "I'm looking for my wallet.",
  "着": "She smiled at me.",
  "真": "This is really delicious.",
  "正在": "I'm cooking.",
  "知道": "I understand.",
  "准备": "I'm preparing for the exam.",
  "自行车": "I bike to school.",
  "走": "Let's go.",
  "最": "I like apples the most.",
  "左边": "The bathroom is on the left.",

  // ===== HSK 3 =====
  "阿姨": "Hello, auntie.",
  "啊": "Ah, that's great!",
  "矮": "He is short.",
  "爱好": "My hobby is reading.",
  "安静": "Please keep quiet.",
  "把": "Please close the door.",
  "班": "Our class has 30 students.",
  "搬": "I'm moving next month.",
  "办法": "I have a good idea.",
  "办公室": "The manager is in the office.",
  "半": "It's 7:30 now.",
  "帮忙": "Can you help me?",
  "包": "I lost my bag.",
  "饱": "I'm full.",
  "北方": "The north is cold in winter.",
  "被": "My book was taken by my brother.",
  "鼻子": "Her nose is high.",
  "比较": "It's relatively cold today.",
  "比赛": "There's a soccer match tomorrow.",
  "必须": "You must come on time.",
  "变化": "The weather has changed a lot.",
  "表示": "He expressed agreement.",
  "表演": "Her performance is wonderful.",
  "别人": "Don't laugh at others.",
  "宾馆": "I'm staying at a hotel.",
  "冰箱": "There's fruit in the fridge.",
  "才": "He only arrived at 10.",
  "菜单": "Please give me the menu.",
  "参加": "I attended the meeting.",
  "草": "There's a lot of grass in the park.",
  "层": "I live on the 3rd floor.",
  "差": "It's five to eight.",
  "超市": "I'm going to the supermarket to buy things.",
  "衬衫": "This shirt is pretty.",
  "成绩": "His grades are good.",
  "城市": "Beijing is a big city.",
  "迟到": "Sorry, I'm late.",
  "出现": "A problem appeared.",
  "除了": "Except for me, everyone went.",
  "厨房": "Mom is cooking in the kitchen.",
  "春": "I like spring.",
  "词语": "What does this word mean?",
  "聪明": "She is very smart.",
  "打扫": "I clean my room every day.",
  "打算": "I plan to travel.",
  "带": "Please bring your passport.",
  "担心": "Don't worry, I'm fine.",
  "蛋糕": "I like to eat cake.",
  "当然": "Of course.",
  "地": "He studies diligently.",
  "地方": "This place is beautiful.",
  "地铁": "I take the subway to work.",
  "地图": "I'm finding the way on the map.",
  "灯": "Please turn off the light.",
  "低": "The temperature is low here.",
  "电梯": "Please take the elevator up.",
  "电子": "I have an email.",
  "东": "The sun rises in the east.",
  "冬": "Winter is cold.",
  "动物": "I like animals.",
  "短": "These pants are too short.",
  "段": "This stretch of road is long.",
  "锻炼": "I exercise every day.",
  "多么": "How beautiful she is!",
  "饿": "I'm very hungry.",
  "而且": "She is smart and pretty.",
  "耳朵": "His ears are big.",
  "发烧": "My son has a fever.",
  "发现": "I found a problem.",
  "方便": "Taking the subway is convenient.",
  "放": "Please put the book on the table.",
  "放心": "Don't worry, I'll do it well.",
  "分": "Please split this into two parts.",
  "附近": "There's a park near my home.",
  "复习": "I review lessons every day.",
  "敢": "I don't dare to say.",
  "感冒": "I caught a cold.",
  "干净": "The room is clean.",
  "刚才": "Someone came just now.",
  "根据": "According to the forecast, it'll rain tomorrow.",
  "跟": "I'm going with you.",
  "更": "Today is colder than yesterday.",
  "公园": "Let's go for a walk in the park.",
  "故事": "He told a story.",
  "刮": "It's very windy today.",
  "关": "Please close the window.",
  "关系": "We have a good relationship.",
  "关心": "Thanks for your concern.",
  "关于": "This is a book about history.",
  "国家": "China is a big country.",
  "果汁": "Please give me a glass of juice.",
  "过去": "I used to live here.",
  "还是": "Do you want tea or coffee?",
  "害怕": "I'm afraid of exams.",
  "河": "This river is long.",
  "黑板": "The teacher is writing on the blackboard.",
  "护照": "Please show your passport.",
  "花": "This flower is pretty.",
  "花园": "My home has a garden.",
  "画": "She draws well.",
  "坏": "My computer is broken.",
  "环境": "The environment here is good.",
  "换": "Please help me exchange money.",
  "黄": "I like yellow.",
  "会议": "There's an important meeting tomorrow.",
  "或者": "Tea or coffee?",
  "机会": "This is a good opportunity.",
  "极": "It's extremely hot today.",
  "几乎": "I go almost every day.",
  "记得": "I remember him.",
  "季节": "Spring is the best season.",
  "检查": "Please check the homework.",
  "简单": "This question is simple.",
  "见面": "Let's meet tomorrow.",
  "健康": "Wishing you good health.",
  "讲": "Please tell this story.",
  "角": "The corner of the table is sharp.",
  "脚": "My foot hurts.",
  "教": "She teaches Chinese.",
  "接": "I'm going to the airport to pick him up.",
  "街道": "This street is busy.",
  "节目": "I like this program.",
  "节日": "Spring Festival is an important holiday.",
  "结婚": "They got married last year.",
  "结束": "Class is over.",
  "解决": "We solved the problem.",
  "借": "I borrowed a book.",
  "经常": "I often go to the library.",
  "经过": "I passed by a bookstore.",
  "经理": "He is the company manager.",
  "久": "Long time no see.",
  "旧": "This is an old book.",
  "举行": "We held a meeting.",
  "句子": "Please translate this sentence.",
  "决定": "I decided to go to China.",
  "可爱": "This puppy is cute.",
  "渴": "I'm thirsty.",
  "刻": "It's 3:15 now.",
  "客人": "Guests came to the house.",
  "空调": "Please turn on the AC.",
  "口": "Please open your mouth.",
  "哭": "The child is crying.",
  "裤子": "How much are these pants?",
  "筷子": "I eat with chopsticks.",
  "蓝": "The sky is blue.",
  "老": "His grandpa is very old.",
  "了解": "I understand him.",
  "离开": "He left Beijing.",
  "礼物": "This is a gift for you.",
  "历史": "I like Chinese history.",
  "脸": "Her face turned red.",
  "练习": "I practice Chinese every day.",
  "辆": "I bought a car.",
  "邻居": "I have a good relationship with my neighbors.",
  "楼": "My home is on the 5th floor.",
  "绿": "Leaves are green.",
  "马": "I can ride a horse.",
  "马上": "I'm coming right away.",
  "满意": "I'm very satisfied.",
  "帽子": "He's wearing a hat.",
  "米": "I'm 5cm taller than him.",
  "面包": "I eat bread in the morning.",
  "面条": "I like to eat noodles.",
  "明白": "I understand.",
  "拿": "Please bring the book over.",
  "奶奶": "Grandma is healthy.",
  "南": "The south has warm weather.",
  "难": "Chinese is hard to learn.",
  "难过": "I'm sad to hear this news.",
  "年级": "My older brother is in 3rd grade.",
  "年轻": "She looks young.",
  "鸟": "Birds fly in the sky.",
  "努力": "I'll study hard.",
  "爬山": "Let's go hiking this weekend.",
  "盘子": "Please give me a plate.",
  "胖": "He's gotten fat lately.",
  "啤酒": "I'm drinking a glass of beer.",
  "葡萄": "I like to eat grapes.",
  "普通话": "She speaks Mandarin well.",
  "其实": "Actually, I don't know either.",
  "其他": "Any other questions?",
  "奇怪": "This is really strange.",
  "骑": "I can ride a bicycle.",
  "清楚": "Am I being clear?",
  "秋": "Fall weather is nice.",
  "裙子": "She's wearing a white skirt.",
  "然后": "I eat first, then do homework.",
  "热情": "He is kind to me.",
  "认为": "I think he is right.",
  "认真": "He studies seriously.",
  "容易": "This question is easy.",
  "如果": "If it rains, I won't go.",
  "伞": "Please bring an umbrella.",
  "上网": "I go online every day.",
  "生气": "Mom is angry.",
  "声音": "Your voice is nice.",
  "使": "This made me happy.",
  "世界": "The world is big.",
  "瘦": "She's gotten thin lately.",
  "叔叔": "This is my uncle.",
  "舒服": "I don't feel well today.",
  "树": "There's a tree in front of the door.",
  "数学": "I'm not good at math.",
  "刷": "I brush my teeth every day.",
  "双": "I bought a pair of shoes.",
  "水平": "Her Chinese level is high.",
  "司机": "He is a taxi driver.",
  "虽然": "Though tired, I'm happy.",
  "太阳": "The sun is strong today.",
  "糖": "I don't like to eat candy.",
  "特别": "I especially like this.",
  "疼": "My head hurts.",
  "提高": "I want to improve my Chinese.",
  "体育": "I like PE class.",
  "甜": "This cake is really sweet.",
  "条": "I bought a pair of pants.",
  "同事": "He is my colleague.",
  "同意": "I agree with your opinion.",
  "头发": "Her hair is long.",
  "突然": "He came suddenly.",
  "图书馆": "I study at the library.",
  "腿": "My legs hurt.",
  "完成": "I finished the homework.",
  "碗": "Please give me a bowl.",
  "万": "This car is 10,000 yuan.",
  "忘记": "I forgot his name.",
  "为了": "I exercise every day for health.",
  "为什么": "Why aren't you coming?",
  "位": "This is Teacher Wang.",
  "文化": "I like Chinese culture.",
  "习惯": "I'm used to getting up early.",
  "洗手间": "Where is the bathroom?",
  "洗澡": "I shower every night.",
  "西": "The sun sets in the west.",
  "夏": "Summer is hot.",
  "先": "Let's eat first.",
  "相同": "His hobby is the same as mine.",
  "相信": "I believe you.",
  "香蕉": "I like to eat bananas.",
  "像": "She looks like her mom.",
  "小心": "Please be careful.",
  "校长": "Our principal is great.",
  "鞋": "These shoes are comfortable.",
  "新闻": "I watch the news every day.",
  "新鲜": "These fruits are fresh.",
  "信": "I received a letter.",
  "行李箱": "This is my suitcase.",
  "兴趣": "I'm interested in history.",
  "熊猫": "China has pandas.",
  "需要": "I need your help.",
  "选择": "I chose this book.",
  "眼镜": "I wear glasses.",
  "要求": "His demands are high.",
  "爷爷": "Grandpa is 80 this year.",
  "一般": "This shop is so-so.",
  "一边": "He watches TV while eating.",
  "一定": "I will definitely come.",
  "一共": "How much in total?",
  "一会儿": "Please wait a moment.",
  "一样": "Our thoughts are the same.",
  "一直": "I've been waiting for you.",
  "以后": "Let's eat after class.",
  "以前": "I couldn't speak Chinese before.",
  "以为": "I thought you weren't coming.",
  "音乐": "I like listening to music.",
  "银行": "Where is the bank?",
  "应该": "You should rest more.",
  "影响": "This matter has a big impact.",
  "用": "I eat with chopsticks.",
  "游戏": "The children are playing a game.",
  "有名": "This restaurant is famous.",
  "又": "He came again.",
  "遇到": "I ran into him on the road.",
  "愿意": "I'm willing to help you.",
  "月亮": "The moon is round tonight.",
  "越": "The rain is getting heavier.",
  "云": "There are white clouds in the sky.",
  "站": "Please stand up.",
  "照顾": "Mom takes care of the child.",
  "照片": "Let's take a picture together.",
  "照相机": "This is a new camera.",
  "着急": "Don't be anxious, take your time.",
  "只": "I only have one question.",
  "中间": "He sits between us.",
  "终于": "I finally finished.",
  "种": "I like this kind of fruit.",
  "重要": "This is important.",
  "周末": "What do you do on weekends?",
  "主要": "This is the main reason.",
  "注意": "Please pay attention to safety.",
  "祝": "Happy birthday.",
  "字典": "Please lend me a dictionary.",
  "自己": "I'll do it myself.",
  "总是": "He's always late.",
  "最近": "How have you been lately?",
  "作业": "I'm doing homework.",
  "作用": "This medicine works.",

  // ===== HSK 4 =====
  "爱情": "Their love is romantic.",
  "安排": "I arranged next week's meeting.",
  "安全": "Please pay attention to safety.",
  "按时": "Please come on time.",
  "按照": "Proceed according to plan.",
  "暗": "The room is too dark.",
  "包括": "The cost includes breakfast.",
  "保护": "We should protect the environment.",
  "保证": "I promise not to be late.",
  "报道": "The newspaper reported this.",
  "报名": "I signed up for the competition.",
  "抱": "Mom is holding the baby.",
  "抱歉": "Sorry to keep you waiting.",
  "倍": "His salary is twice mine.",
  "本来": "I originally wanted to go.",
  "笨": "I'm really stupid.",
  "笔记本": "I bought a new notebook.",
  "毕业": "I graduated from university last year.",
  "遍": "Please say it once more.",
  "标准": "Her pronunciation is standard.",
  "表达": "I can't express my feelings.",
  "表格": "Please fill out this form.",
  "表扬": "The teacher praised him.",
  "饼干": "I like to eat cookies.",
  "并且": "She is smart and hardworking.",
  "博士": "He has a PhD.",
  "不但": "He's not only smart but also hardworking.",
  "不得不": "I have no choice but to leave.",
  "不管": "No matter how tired, I must go.",
  "不过": "He's good, but a bit lazy.",
  "不仅": "He knows not only Chinese but also Japanese.",
  "部分": "I don't understand this part.",
  "擦": "Please wipe the table.",
  "猜": "Guess who I am.",
  "材料": "Please prepare the materials.",
  "参观": "Let's visit the museum.",
  "差不多": "We're almost there.",
  "尝": "Try this.",
  "场": "I watched a movie.",
  "超过": "He surpassed me.",
  "吵": "It's too noisy outside.",
  "成功": "Wishing you success.",
  "成熟": "The apples aren't ripe yet.",
  "成为": "I want to become a doctor.",
  "诚实": "He is an honest person.",
  "乘坐": "I'm flying to Beijing.",
  "吃惊": "I was surprised to hear the news.",
  "抽烟": "Please don't smoke.",
  "出差": "I'm going to Beijing for business next week.",
  "出发": "We leave at 8.",
  "出生": "I was born in Korea.",
  "传真": "Please send a fax.",
  "窗户": "Please open the window.",
  "词典": "I look up words in the dictionary.",
  "从来": "I have never been there.",
  "粗心": "He does things carelessly.",
  "答案": "The answer is correct.",
  "打扮": "She dressed up beautifully.",
  "打扰": "Sorry to bother you.",
  "打印": "Please print this document.",
  "打折": "These clothes are on sale.",
  "打针": "The doctor gave me a shot.",
  "大夫": "Doctor, where am I sick?",
  "大概": "I can arrive around 10.",
  "大使馆": "I'm going to the embassy for a visa.",
  "大约": "About an hour.",
  "代表": "I represent the company at the meeting.",
  "代替": "Go in my place.",
  "戴": "He's wearing glasses.",
  "弹": "She can play the piano.",
  "当": "I'll become a teacher.",
  "当地": "He's a local.",
  "当时": "I was still young then.",
  "刀": "Please cut with a knife.",
  "导游": "The guide explained in detail.",
  "到处": "I looked for you everywhere.",
  "到底": "What on earth do you want?",
  "道歉": "You should apologize to him.",
  "地球": "The earth is round.",
  "地址": "Please tell me your address.",
  "得意": "He laughed proudly.",
  "等": "I'll treat you to a meal, movies, etc.",
  "底": "There's some water at the bottom of the cup.",
  "调查": "The police are investigating.",
  "掉": "I dropped my phone.",
  "丢": "I lost my wallet.",
  "动作": "His movements are quick.",
  "堵车": "There's traffic again today.",
  "肚子": "My stomach hurts.",
  "断": "The phone disconnected.",
  "对话": "Please listen to the dialogue.",
  "对面": "He sits across from me.",
  "顿": "I eat three meals a day.",
  "朵": "He gave me a flower.",
  "儿童": "Children can't enter.",
  "而": "He's smart, but I'm stupid.",
  "发": "Please send me an email.",
  "发生": "What happened?",
  "发展": "The economy is developing fast.",
  "法律": "We must follow the law.",
  "翻译": "Please help me translate.",
  "烦恼": "I have many worries.",
  "反对": "I oppose this opinion.",
  "反映": "This reflects the real situation.",
  "范围": "This is outside my scope.",
  "方法": "I have a good method.",
  "方面": "I'm not familiar with this aspect.",
  "方向": "You went the wrong direction.",
  "访问": "The president visits China.",
  "放弃": "Don't give up easily.",
  "放暑假": "School is on summer vacation.",
  "分之": "One-third is mine.",
  "份": "I want a newspaper.",
  "丰富": "He has rich experience.",
  "风景": "The scenery here is beautiful.",
  "否则": "Hurry up, otherwise we'll be late.",
  "符合": "This conforms to the regulations.",
  "父亲": "My father is a teacher.",
  "负责": "He's in charge of this project.",
  "复印": "Please make a copy.",
  "复杂": "This problem is complicated.",
  "富": "His family is rich.",
  "改变": "I want to change myself.",
  "感动": "I'm very touched.",
  "感觉": "I feel good.",
  "感情": "They have deep feelings.",
  "感谢": "Thank you for your help.",
  "干": "The clothes are dry.",
  "干杯": "Cheers to friendship.",
  "干燥": "The climate here is dry.",
  "刚刚": "He just left.",
  "高级": "This is a high-end restaurant.",
  "个子": "He is tall.",
  "各": "Everyone, please pay attention.",
  "工具": "This is a necessary tool.",
  "工资": "I get paid monthly.",
  "公里": "The school is 5 km from home.",
  "共同": "We have common hobbies.",
  "购物": "I like shopping.",
  "够": "Not enough money.",
  "估计": "I guess he won't come.",
  "孤单": "I'm lonely alone.",
  "鼓励": "Mom encouraged me.",
  "鼓掌": "Everyone applauded in welcome.",
  "故意": "I didn't do it on purpose.",
  "顾客": "The customer is king.",
  "挂": "A picture is hanging on the wall.",
  "关键": "This is the key question.",
  "观众": "There's a lot of audience.",
  "管理": "He manages this company.",
  "光": "Please turn off the light, it's too bright.",
  "广播": "I listen to the radio every day.",
  "广告": "This ad is interesting.",
  "逛": "I like to walk the streets.",
  "规定": "Please follow the rules.",
  "国际": "This is an international airport.",
  "果然": "It really did rain.",
  "过": "I've been to China.",
  "过程": "This is a process.",
  "咳嗽": "I cough from a cold.",
  "海洋": "The ocean is vast.",
  "害羞": "She is shy.",
  "寒假": "I'm traveling during winter break.",
  "汗": "I sweated a lot.",
  "航班": "My flight was delayed.",
  "好处": "Exercise has benefits.",
  "好像": "It looks like it's going to rain.",
  "号码": "What is your phone number?",
  "合格": "You passed the exam.",
  "合适": "These clothes fit well.",
  "盒子": "What's in the box?",
  "猴子": "There are monkeys in the zoo.",
  "后悔": "I regret it now.",
  "后来": "What happened to him later?",
  "厚": "This book is thick.",
  "忽然": "Suddenly it rained.",
  "互相": "We help each other.",
  "护士": "The nurse is kind.",
  "怀疑": "I suspect he is lying.",
  "回忆": "I recalled my childhood.",
  "活动": "There's an event today.",
  "活泼": "She is lively.",
  "火": "Please be careful with fire.",
  "获得": "He got first place.",
  "积极": "He works actively.",
  "积累": "We should accumulate experience.",
  "基础": "The foundation is important.",
  "激动": "I'm so excited.",
  "及时": "Please reply in time.",
  "即使": "Even if it rains, I'll go.",
  "极其": "This is extremely important.",
  "集合": "Everyone, please gather.",
  "计划": "I have a plan.",
  "记者": "He is a reporter.",
  "技术": "His skills are good.",
  "既然": "Since you're here, sit down.",
  "继续": "Please continue speaking.",
  "寄": "I sent a letter.",
  "加班": "I'm working overtime today.",
  "加油站": "I'm going to the gas station.",
  "家具": "The new home needs furniture.",
  "假": "This is fake.",
  "价格": "The price is too high.",
  "坚持": "I'll keep going.",
  "减肥": "I'm losing weight.",
  "减少": "Please reduce the noise.",
  "将来": "What do you want to do in the future?",
  "奖金": "I got the bonus.",
  "降低": "Please lower your voice.",
  "交": "Please submit your homework.",
  "交流": "We exchange often.",
  "交通": "Transportation here is convenient.",
  "骄傲": "I'm proud of you.",
  "饺子": "I like to eat dumplings.",
  "教授": "He is a university professor.",
  "教育": "Education is important.",
  "接受": "I accept your invitation.",
  "节约": "Please save water.",
  "结果": "The result is okay.",
  "解释": "Please explain.",
  "尽管": "Although tired, he still went.",
  "紧张": "I'm nervous before the exam.",
  "进行": "The meeting is in progress.",
  "禁止": "No smoking here.",
  "京剧": "I like watching Beijing opera.",
  "经济": "China's economy is developing fast.",
  "经历": "I've experienced a lot.",
  "经验": "He has rich experience.",
  "精彩": "The performance was great.",
  "精神": "He is in good spirits.",
  "警察": "Please call the police.",
  "竞争": "The market competition is fierce.",
  "竟然": "He unexpectedly didn't come.",
  "镜子": "She's looking in the mirror.",
  "究竟": "What on earth happened?",
  "举办": "We held a party.",
  "拒绝": "He rejected my invitation.",
  "距离": "The distance isn't far.",
  "开玩笑": "I was joking with you.",
  "看法": "What is your view?",
  "考虑": "Let me think about it.",
  "科学": "I like science.",
  "棵": "There's a tree at the entrance.",
  "可怜": "This puppy is so pitiful.",
  "可是": "I want to go, but I don't have time.",
  "可惜": "That's a pity.",
  "肯定": "He will definitely come.",
  "空气": "The air on the mountain is good.",
  "恐怕": "I'm afraid it's too late.",
  "苦": "This medicine is bitter.",
  "宽": "This road is wide.",
  "困": "I'm sleepy.",
  "困难": "This is a difficult problem.",
  "扩大": "The company expanded its scale.",
  "垃圾桶": "Where is the trash can?",
  "拉": "Please pull the door.",
  "辣": "This dish is spicy.",
  "来不及": "No time, hurry up.",
  "来得及": "There's still time if I go now.",
  "懒": "He's lazy.",
  "浪费": "Please don't waste.",
  "浪漫": "This is a romantic story.",
  "老虎": "Tigers are dangerous.",
  "冷静": "Please calm down.",
  "礼貌": "He has good manners.",
  "理发": "I'm going for a haircut.",
  "理解": "I understand you.",
  "理想": "His dream is to be a doctor.",
  "力气": "He is strong.",
  "厉害": "You're really amazing.",
  "例如": "For example, apples and bananas.",
  "俩": "The two of us are friends.",
  "连": "He didn't even eat.",
  "联系": "Please keep in touch.",
  "凉快": "It's cool today.",
  "亮": "The light is bright.",
  "聊天": "Let's chat.",
  "另外": "Also, I have one more thing.",
  "流泪": "She cried tears of emotion.",
  "流利": "He speaks Chinese fluently.",
  "流行": "This song is popular.",
  "留": "Please leave your phone number.",
  "留学": "I want to study abroad in China.",
  "律师": "He is a lawyer.",
  "乱": "The room is too messy.",
  "麻烦": "Sorry to trouble you.",
  "马虎": "He does things carelessly.",
  "满": "The cup is full.",
  "毛巾": "Please give me a towel.",
  "美丽": "It's very beautiful here.",
  "梦": "I had a dream.",
  "密码": "Please enter your password.",
  "免费": "This is free.",
  "民族": "China has many ethnic groups.",
  "母亲": "My mother is a doctor.",
  "目的": "What is your purpose?",
  "耐心": "He has patience.",
  "难道": "Don't tell me you don't know?",
  "难受": "I feel terrible.",
  "内": "Please discuss internally.",
  "内容": "The content of this book is good.",
  "能力": "His work ability is strong.",
  "年龄": "He's not old.",
  "农村": "I grew up in the countryside.",
  "弄": "What are you doing?",
  "暖和": "It's warm today.",
  "偶尔": "I occasionally drink.",
  "排列": "Please arrange in order.",
  "判断": "I can't judge.",
  "陪": "I'll go to the hospital with you.",
  "批评": "The teacher criticized him.",
  "皮肤": "Her skin is fair.",
  "脾气": "He has a bad temper.",
  "篇": "I wrote an article.",
  "骗": "He deceived me.",
  "乒乓球": "Chinese people like table tennis.",
  "平时": "I usually don't drink.",
  "瓶子": "There's a bottle on the table.",
  "破": "My clothes are torn.",
  "普遍": "This problem is common.",
  "其次": "First is health, then work.",
  "其中": "One of them is mine.",
  "起飞": "The plane took off.",
  "起来": "Please get up.",
  "气候": "The climate here is good.",
  "千万": "You must be careful.",
  "签证": "I got my visa.",
  "墙": "There's a picture on the wall.",
  "敲": "Someone is knocking on the door.",
  "桥": "This bridge is long.",
  "巧克力": "I like chocolate.",
  "亲戚": "I'm going to see relatives.",
  "轻": "This bag is light.",
  "轻松": "This job is easy.",
  "情况": "How's the situation?",
  "请假": "I took one day off.",
  "请客": "I'll treat today.",
  "穷": "His family is poor.",
  "区别": "There's a difference between the two.",
  "取": "I'm going to the bank to withdraw money.",
  "全部": "I ate it all.",
  "缺点": "Everyone has flaws.",
  "缺少": "We lack time.",
  "却": "He promised but didn't come.",
  "确实": "He really is a good person.",
  "群": "A group of students are on the playground.",
  "然而": "He studied hard, but didn't do well.",
  "热闹": "The square is lively.",
  "人民币": "Please pay in RMB.",
  "任何": "No one can enter.",
  "任务": "I have an important task.",
  "扔": "Please throw the trash in the bin.",
  "仍然": "He's still waiting.",
  "日记": "I write a diary every day.",
  "入口": "Where's the entrance?",
  "软": "This pillow is soft.",
  "散步": "Let's go for a walk in the park.",
  "森林": "There are many animals in the forest.",
  "沙发": "Please sit on the sofa.",
  "伤心": "She cried sadly.",
  "商量": "Let's discuss.",
  "稍微": "Please wait a moment.",
  "社会": "Society is changing.",
  "申请": "I'm applying for a scholarship.",
  "深": "This river is deep.",
  "甚至": "Even I don't know.",
  "生活": "My life is simple.",
  "生命": "Life is precious.",
  "省": "I saved a lot of money.",
  "剩": "Two apples left.",
  "失败": "Failure is the mother of success.",
  "失望": "I'm disappointed.",
  "师傅": "Driver, take me to the airport.",
  "狮子": "Lions are strong.",
  "湿润": "The air is moist.",
  "十分": "I'm very happy.",
  "实际": "This is unrealistic.",
  "实在": "I really have no way.",
  "食品": "This shop sells food.",
  "使用": "Please use correctly.",
  "世纪": "The 21st century is the information age.",
  "市场": "I'm going to the market to buy groceries.",
  "试": "Give it a try.",
  "适合": "These clothes suit you.",
  "适应": "I adapted to the new life.",
  "收": "I received the letter.",
  "收入": "His income is high.",
  "收拾": "Please tidy the room.",
  "首都": "Beijing is China's capital.",
  "首先": "First, I want to thank everyone.",
  "受不了": "I can't stand this noise.",
  "受到": "He received criticism.",
  "售货员": "The clerk is friendly.",
  "输": "I lost.",
  "熟悉": "I'm familiar with this place.",
  "数量": "The quantity isn't enough.",
  "数字": "Please write the numbers.",
  "帅": "He is handsome.",
  "顺便": "Please buy it for me on the way.",
  "顺利": "Things are going smoothly.",
  "顺序": "Please enter in order.",
  "说明": "Please explain the reason.",
  "硕士": "He has a master's degree.",
  "死": "My cat died.",
  "速度": "His speed is fast.",
  "塑料袋": "Please use a plastic bag.",
  "酸": "This lemon is sour.",
  "算": "Please calculate.",
  "随便": "Sit anywhere.",
  "随着": "I forgot as time passed.",
  "孙子": "He's holding his grandson.",
  "所有": "Everyone came.",
  "台": "I bought a computer.",
  "抬": "Please lift this table.",
  "态度": "His attitude is good.",
  "谈": "Let's talk.",
  "汤": "This soup is delicious.",
  "躺": "I want to lie down and rest.",
  "趟": "I went once.",
  "讨论": "Let's discuss.",
  "讨厌": "I hate being late.",
  "特点": "This is his characteristic.",
  "提供": "We offer free service.",
  "提前": "Please arrive in advance.",
  "提醒": "Please remind me.",
  "填空": "Please fill in the blanks.",
  "条件": "The conditions are good.",
  "停止": "Please stop talking.",
  "挺": "It's pretty cold today.",
  "通过": "I passed the exam.",
  "通知": "I'll notify everyone.",
  "同情": "I sympathize with her.",
  "推": "Please push the door.",
  "推迟": "The meeting was postponed to next week.",
  "脱": "Please take off your shoes.",
  "袜子": "I bought new socks.",
  "完全": "I completely agree.",
  "网球": "I can play tennis.",
  "网站": "This website is useful.",
  "往": "Please go forward.",
  "往往": "He's often busy.",
  "危险": "It's dangerous here.",
  "味道": "This taste is good.",
  "温度": "The temperature is high today.",
  "文章": "I wrote an article.",
  "握手": "Let's shake hands.",
  "污染": "Air pollution is serious.",
  "无": "I have nothing to say.",
  "无聊": "I'm bored.",
  "无论": "No matter what you say, I won't go.",
  "误会": "You misunderstood me.",
  "吸引": "This book attracts me.",
  "洗衣机": "The washing machine is broken.",
  "西红柿": "I like tomatoes.",
  "咸": "This dish is too salty.",
  "现代": "Modern life is convenient.",
  "限制": "Time is limited.",
  "羡慕": "I envy you.",
  "相反": "My thoughts are opposite.",
  "香": "This flower is fragrant.",
  "详细": "Please explain in detail.",
  "响": "The phone rang.",
  "消息": "This is good news.",
  "小说": "I like to read novels.",
  "效果": "The effect is good.",
  "笑话": "Let me tell you a joke.",
  "心情": "I'm in a bad mood.",
  "辛苦": "You've worked hard.",
  "信任": "I trust you.",
  "信心": "I have confidence.",
  "信用卡": "I'll pay with credit card.",
  "行": "Is this okay?",
  "醒": "I woke up.",
  "兴奋": "I'm excited.",
  "幸福": "Wishing you happiness.",
  "性别": "Please fill in your gender.",
  "性格": "She has a cheerful personality.",
  "修": "I fixed the computer.",
  "许多": "Many people are queuing.",
  "血": "He bled.",
  "压力": "I'm under a lot of pressure.",
  "牙膏": "The toothpaste ran out.",
  "亚洲": "Korea is in Asia.",
  "呀": "How pretty!",
  "严格": "The teacher is strict.",
  "严重": "The situation is serious.",
  "研究生": "She's a graduate student.",
  "盐": "Please give me salt.",
  "演出": "There's a performance tonight.",
  "演员": "She is a famous actress.",
  "阳光": "The sunshine is nice today.",
  "养成": "Develop good habits.",
  "样子": "His appearance is strange.",
  "邀请": "I invite you to come.",
  "钥匙": "I can't find my keys.",
  "也许": "Maybe it'll rain.",
  "叶子": "Leaves turn yellow in autumn.",
  "页": "Please turn to page 10.",
  "一切": "Everything is fine.",
  "以": "Focusing on studies.",
  "亿": "China has over a billion people.",
  "艺术": "I like art.",
  "意见": "I have a different opinion.",
  "因此": "It rained, so I didn't go.",
  "引起": "This drew my attention.",
  "饮料": "What drink do you want?",
  "印象": "He made a good impression on me.",
  "赢": "We won.",
  "硬": "The bread is too hard.",
  "永远": "I'll love you forever.",
  "勇敢": "He is brave.",
  "优点": "He has many strengths.",
  "优秀": "She is an excellent student.",
  "幽默": "He is humorous.",
  "尤其": "I like fruits, especially apples.",
  "由": "He's in charge of this matter.",
  "由于": "Due to bad weather, the game was canceled.",
  "有趣": "This story is interesting.",
  "友好": "He is friendly to people.",
  "友谊": "Our friendship is deep.",
  "于是": "It rained, so I went home.",
  "愉快": "Have a pleasant trip.",
  "与": "I go with him.",
  "羽毛球": "I like to play badminton.",
  "语法": "Chinese grammar isn't too hard.",
  "语言": "I've learned many languages.",
  "预习": "Please preview the lesson.",
  "原来": "It turns out you were here.",
  "原谅": "Please forgive me.",
  "原因": "The reason is complicated.",
  "圆": "The moon is round.",
  "约会": "I have an appointment.",
  "阅读": "I like reading.",
  "允许": "No smoking allowed here.",
  "杂志": "I read magazines every week.",
  "咱们": "Let's go together.",
  "暂时": "I won't go for now.",
  "脏": "Your clothes are dirty.",
  "责任": "This is my responsibility.",
  "增加": "Salary increased.",
  "增长": "The economy is growing.",
  "窄": "This road is narrow.",
  "长城": "I've been to the Great Wall.",
  "长江": "The Yangtze River is long.",
  "招聘": "Our company is hiring.",
  "著名": "He is a famous author.",
  "真正": "He is a true friend.",
  "整理": "Please tidy the table.",
  "整齐": "The room is tidy.",
  "正常": "Everything is normal.",
  "正好": "You came at just the right time.",
  "正确": "The answer is correct.",
  "正式": "This is a formal event.",
  "证明": "Please prove your identity.",
  "之": "This is my love.",
  "支持": "I support you.",
  "知识": "Knowledge is power.",
  "直接": "Please tell me directly.",
  "值得": "This book is worth reading.",
  "职业": "What's your profession?",
  "植物": "I like to grow plants.",
  "只好": "I had no choice but to go.",
  "只要": "As long as you try, you can succeed.",
  "指": "He pointed with his hand.",
  "至少": "There are at least 10 people.",
  "制造": "This is made in China.",
  "质量": "The quality is good.",
  "中文": "I'm learning Chinese.",
  "重点": "Please remember the key points.",
  "重视": "He values family.",
  "重新": "Please start over.",
  "周围": "There are many trees around.",
  "猪": "He raised a pig.",
  "逐渐": "The weather is gradually warming.",
  "主动": "He is proactive.",
  "主意": "That's a good idea.",
  "祝贺": "Congratulations!",
  "专门": "He specializes in history.",
  "专业": "My major is Chinese.",
  "赚": "He earned a lot of money.",
  "撞": "I bumped into the door.",
  "准确": "The time is accurate.",
  "准时": "Please come on time.",
  "仔细": "Please look carefully.",
  "自然": "I like nature.",
  "总结": "Please summarize.",
  "租": "I rented a house.",
  "组成": "We formed a team.",
  "组织": "We organized an event.",
  "嘴": "Open your mouth.",
  "最好": "You'd better come early.",
  "最后": "In the end we won.",
  "尊重": "Please respect others.",
  "作者": "Who is the author of this book?",
  "座": "This mountain is tall.",
  "座位": "Please sit in this seat.",
  "做生意": "He is doing business.",

  // ===== HSK 5 Part 1 =====
  "唉": "Sigh, I'm late again.",
  "爱护": "Please take care of public facilities.",
  "爱惜": "We should cherish time.",
  "爱心": "He's a person with love.",
  "安慰": "She comforted me.",
  "安装": "I installed new software.",
  "岸": "We walked to the shore.",
  "把握": "I'm not confident.",
  "摆": "Flowers are placed on the table.",
  "班主任": "Our homeroom teacher is strict.",
  "办理": "I'm going to the bank to handle business.",
  "傍晚": "I like to walk in the evening.",
  "棒": "He's really good at basketball.",
  "包裹": "I received a package.",
  "包含": "The price includes tax.",
  "包子": "I eat steamed buns in the morning.",
  "薄": "This book is thin.",
  "宝贝": "The child is my treasure.",
  "宝贵": "Time is precious.",
  "保持": "Please keep quiet.",
  "保存": "Please save the file.",
  "保留": "I reserve my opinion.",
  "保险": "I bought health insurance.",
  "报告": "I wrote a report.",
  "悲观": "He's pessimistic about the future.",
  "背": "Please memorize the words.",
  "背景": "His family background is good.",
  "被子": "Cover with the blanket at night.",
  "本科": "I finished my undergraduate degree.",
  "本领": "He has many talents.",
  "本质": "See the essence clearly.",
  "比例": "The gender ratio is balanced.",
  "比如": "Like apples and bananas.",
  "彼此": "We know each other well.",
  "必然": "Success is inevitable.",
  "必需": "Water is a necessity.",
  "必要": "No need to worry.",
  "毕竟": "After all, he's a child.",
  "避免": "Avoid mistakes.",
  "编辑": "He is an editor.",
  "鞭炮": "Set off firecrackers during Spring Festival.",
  "便": "Cheap and convenient.",
  "辩论": "We're debating.",
  "标点": "Please pay attention to punctuation.",
  "标志": "This is the company logo.",
  "表面": "The table surface is smooth.",
  "表明": "He stated his position.",
  "表情": "Her expression is strange.",
  "表现": "He performed well.",
  "丙": "Bing is the third.",
  "病毒": "The computer got a virus.",
  "玻璃": "The window is glass.",
  "脖子": "My neck hurts.",
  "博物馆": "I'm going to visit the museum.",
  "补充": "Please add more explanation.",
  "不安": "I feel uneasy.",
  "不必": "No need to worry.",
  "不得了": "This is a big deal.",
  "不断": "He keeps improving.",
  "不好意思": "Sorry to bother you.",
  "不见得": "He won't necessarily come.",
  "不免": "I can't help worrying.",
  "不耐烦": "He looks impatient.",
  "不然": "Hurry, otherwise we'll be late.",
  "不如": "I'm not as tall as him.",
  "不要紧": "It's nothing, no worries.",
  "不足": "Lack of experience.",
  "布": "This cloth is soft.",
  "步骤": "Please follow the steps.",
  "部门": "Our department has 10 people.",
  "财产": "He has a lot of property.",
  "采访": "The reporter interviewed him.",
  "采取": "We need to take action.",
  "彩虹": "There's a rainbow in the sky.",
  "踩": "Don't step on the grass.",
  "参考": "Please refer to this book.",
  "参与": "I participated in the project.",
  "餐厅": "This restaurant is good.",
  "残疾": "He is disabled.",
  "惭愧": "I feel ashamed.",
  "操场": "Students are running on the playground.",
  "操心": "Mom worries about me.",
  "册": "This is volume one.",
  "厕所": "The toilet is over there.",
  "测验": "There's a test tomorrow.",
  "曾经": "I've been to China before.",
  "叉子": "Please give me a fork.",
  "插": "Please put flowers in the vase.",
  "差别": "The difference between the two isn't big.",
  "拆": "They're tearing down the house.",
  "产品": "Our products are good.",
  "产生": "A misunderstanding arose.",
  "常识": "This is common sense.",
  "抄": "Don't copy the answers.",
  "朝": "Please look forward.",
  "朝代": "Tang Dynasty was a great dynasty.",
  "吵架": "They fought again.",
  "炒": "Mom is stir-frying.",
  "车库": "The car is in the garage.",
  "车厢": "This carriage is crowded.",
  "彻底": "I'm completely disappointed.",
  "沉默": "He fell silent.",
  "趁": "Eat while it's hot.",
  "称呼": "How should I address you?",
  "称赞": "The teacher praised her.",
  "成分": "What's in this medicine?",
  "成果": "Work yields results.",
  "成就": "He achieved success.",
  "成立": "The company was established.",
  "成语": "I learned an idiom.",
  "成长": "The child is growing.",
  "承担": "I take responsibility.",
  "承认": "I admit I was wrong.",
  "承受": "I can't bear it.",
  "诚恳": "His attitude is sincere.",
  "乘": "I take the subway.",
  "程度": "What level is this?",
  "程序": "Follow the procedure.",
  "吃亏": "I lost out.",
  "池子": "There are fish in the pond.",
  "持续": "It rained for three days straight.",
  "尺子": "Please give me a ruler.",
  "翅膀": "Birds have wings.",
  "充电器": "I forgot my charger.",
  "充分": "Please prepare adequately.",
  "充满": "He's full of confidence.",
  "冲": "Please rinse the cup.",
  "宠物": "I like pets.",
  "抽屉": "The pen is in the drawer.",
  "抽象": "This concept is abstract.",
  "丑": "He's ugly.",
  "臭": "This smell is stinky.",
  "出版": "This book was published.",
  "出口": "Where's the exit?",
  "出色": "He does excellent work.",
  "出席": "Please attend the meeting.",
  "初级": "I'm a beginner student.",
  "除": "6 divided by 2 is 3.",
  "除非": "Unless it rains, I won't not go.",
  "除夕": "Family reunites on New Year's Eve.",
  "处理": "I'll handle this matter.",
  "传播": "The news spread quickly.",
  "传递": "Please pass this document.",
  "传染": "Colds are contagious.",
  "传说": "This is a legend.",
  "传统": "This is traditional culture.",
  "窗帘": "Please close the curtains.",
  "闯": "He ran a red light.",
  "创造": "We created a miracle.",
  "吹": "The wind is blowing hard.",
  "辞职": "He quit his job.",
  "磁带": "No one uses cassette tapes now.",
  "此外": "Besides, there's one more thing.",
  "次要": "This is secondary.",
  "刺激": "This is too stimulating.",
  "匆忙": "He left in a hurry.",
  "从此": "After that, he never came back.",
  "从而": "He tried hard and thus succeeded.",
  "从前": "This place used to be a forest.",
  "从事": "He works in education.",
  "促进": "Exercise promotes health.",
  "促使": "This made him change.",
  "醋": "Please give me vinegar.",
  "催": "Mom urged me to get up.",
  "存": "I save money in the bank.",
  "存在": "The problem really exists.",
  "措施": "New measures were taken.",
  "错误": "Please correct the mistakes.",
  "达到": "I reached my goal.",
  "答应": "He promised me.",
  "打工": "I work part-time during vacation.",
  "打交道": "I've dealt with him.",
  "打喷嚏": "I'm sneezing from a cold.",
  "打听": "Let me find out the news.",
  "打招呼": "I greet him.",
  "大方": "She is generous.",
  "大象": "Elephants are big.",
  "大型": "This is a large event.",
  "呆": "He froze.",
  "待遇": "This company has good benefits.",
  "贷款": "I bought a house with a loan.",
  "单纯": "She's naive.",
  "单调": "Life is too monotonous.",
  "单独": "I want to talk with you alone.",
  "单位": "Which company do you work at?",
  "单元": "I live in unit 3.",
  "担任": "He took the position of manager.",
  "耽误": "Sorry to take your time.",
  "胆小鬼": "He's a coward.",
  "淡": "The soup is too bland.",
  "当代": "He's a contemporary writer.",
  "挡": "Please don't block the way.",
  "导演": "He's a famous director.",
  "导致": "This led to failure.",
  "岛": "That island is beautiful.",
  "到达": "We arrived in Beijing.",
  "倒": "Please pour a glass of water.",
  "倒霉": "I'm really unlucky today.",
  "道德": "She is moral.",
  "道理": "What you said makes sense.",
  "地道": "His Chinese is authentic.",
  "地理": "I like geography class.",
  "地区": "This area has many people.",
  "地毯": "The carpet is soft.",
  "地位": "She has high social status.",
  "地震": "There was an earthquake just now.",
  "的确": "It really is so.",
  "登机牌": "Please show your boarding pass.",
  "登记": "Please register.",
  "等待": "I'm waiting for you.",
  "等候": "Please wait a moment.",
  "等于": "Two plus three equals five.",
  "滴": "Water is dripping.",
  "敌人": "He is my enemy.",
  "递": "Please pass me the salt.",
  "点头": "He nodded in agreement.",
  "点心": "Eat snacks in the afternoon.",
  "电池": "The battery is dead.",
  "电台": "I listen to radio news.",
  "钓": "I like fishing.",
  "调皮": "This child is naughty.",
  "调整": "Please adjust a bit.",
  "丁": "He's called Xiao Ding.",
  "顶": "The mountain top is beautiful.",
  "动画片": "Children like to watch cartoons.",
  "冻": "My hands froze.",
  "洞": "There's a hole in the wall.",
  "豆腐": "I like to eat tofu.",
  "逗": "He's teasing the child.",
  "独立": "She is financially independent.",
  "独特": "She has a unique style.",
  "度过": "I had a pleasant day.",
  "短信": "I'll send you a text.",
  "堆": "Books are piled on the desk.",
  "对比": "Compare the two products.",
  "对待": "Please treat seriously.",
  "对方": "What did the other party say?",
  "对手": "He is my opponent.",
  "对象": "She got a partner.",
  "对于": "I have thoughts on this issue.",
  "吨": "This car weighs a ton.",
  "蹲": "He squatted down.",
  "多亏": "Thanks to your help.",
  "多余": "These words are superfluous.",
  "躲藏": "He went into hiding.",
  "恶劣": "The weather is terrible.",
  "发表": "He published a paper.",
  "发愁": "Don't worry.",
  "发达": "It's developed.",
  "发抖": "I'm shivering from cold.",
  "发挥": "Please show your skills.",
  "发明": "He invented a new machine.",
  "发票": "Please give me a receipt.",
  "发言": "Please speak up.",
  "罚款": "He was fined.",
  "法院": "The case went to court.",
  "翻": "Please open the book.",
  "凡是": "All students should work hard.",
  "繁荣": "The economy flourishes.",
  "反而": "He got angry instead.",
  "反复": "Please practice repeatedly.",
  "反应": "He reacts fast.",
  "反正": "Anyway, I'll go.",
  "方": "The table is square.",
  "方案": "We're discussing the plan.",
  "方式": "Use this method.",
  "妨碍": "Please don't hinder me.",
  "房东": "The landlord is nice.",
  "仿佛": "It's like a dream.",
  "放松": "Please relax.",
  "非": "He must go.",
  "肥皂": "Please wash hands with soap.",
  "废话": "Don't talk nonsense.",
  "肺": "Smoking hurts the lungs.",
  "费用": "The cost is high.",
  "分别": "We parted.",
  "分布": "The population distribution is uneven.",
  "分配": "Please assign the tasks.",
  "分析": "Please analyze the data.",
  "纷纷": "Everyone left one after another.",
  "奋斗": "Let's struggle together.",
  "愤怒": "He was very angry.",
  "风格": "She has a unique style.",
  "风俗": "Learn local customs.",
  "风险": "Investment has risks.",
  "疯狂": "He ran madly.",
  "讽刺": "She mocked him.",
  "否定": "I deny this idea.",
  "否认": "He denied it.",
  "扶": "I help the elderly cross the road.",
  "服从": "Please follow orders.",
  "服装": "This shop sells clothing.",
  "幅": "This is a painting.",
  "辅导": "He's tutoring me.",
  "付款": "Please pay.",
  "妇女": "Today is Women's Day.",
  "复制": "Please copy the file.",
  "改革": "The company is reforming.",
  "改进": "We need to improve our work.",
  "改善": "Life has improved.",
  "改正": "Please correct the mistakes.",
  "盖": "Please cover with the blanket.",
  "概括": "Please summarize the content.",
  "概念": "This concept is important.",
  "赶紧": "Set off quickly.",
  "赶快": "Hurry up and go.",
  "感激": "I'm very grateful.",
  "感受": "I felt warmth.",
  "感想": "What are your thoughts?",
  "干脆": "Be more decisive.",
  "干活儿": "He's working.",
  "钢铁": "This is a steel factory.",
  "高档": "This is a luxury product.",
  "高速": "We take the highway.",
  "搞": "What are you doing?",
  "告别": "We bid farewell to friends.",
  "胳膊": "His arm hurts.",
  "鸽子": "There are pigeons in the park.",
  "革命": "This is a revolution.",
  "格外": "It's especially cold today.",
  "隔壁": "Next door is my home.",
  "个别": "Some people disagree.",
  "个人": "Personal opinion.",
  "个性": "She has personality.",
  "各自": "Everyone does their own thing.",
  "根": "The tree roots are deep.",
  "根本": "I don't know at all.",
  "更加": "It's colder today.",
  "工厂": "He works at a factory.",
  "工程师": "He is an engineer.",
  "工人": "The workers are working.",
  "工业": "Industry develops fast.",
  "公布": "The results were announced.",
  "公开": "Please speak publicly.",
  "公平": "This is unfair.",
  "公寓": "I live in an apartment.",
  "公元": "1000 BC.",
  "公主": "She's like a princess.",
  "功夫": "I've learned kung fu.",
  "功能": "This phone has many features.",
  "贡献": "He made contributions.",
  "沟通": "We need to communicate.",
  "构成": "This constitutes a problem.",
  "姑姑": "Aunt lives in Beijing.",
  "姑娘": "She's a pretty girl.",
  "古代": "Ancient China was great.",
  "古典": "I like classical music.",
  "古老": "This is an ancient city.",
  "股票": "I bought stocks.",
  "骨头": "Dogs like bones.",
  "鼓舞": "He inspired everyone.",
  "固定": "This is a fixed time.",
  "固体": "Ice is a solid.",
  "雇佣": "The company hired him.",
  "挂号": "Please register first.",
  "乖": "The child is so good.",
  "拐弯": "Turn ahead.",
  "怪不得": "No wonder he didn't come.",
  "关闭": "The shop closed.",
  "关怀": "He cares about others.",
  "观察": "Please observe carefully.",
  "观点": "What's your viewpoint?",
  "观念": "His ideas are new.",
  "官": "He's a high official.",
  "冠军": "He won the championship.",
  "管子": "The water pipe broke.",
  "罐头": "I opened the can.",
  "光滑": "The table surface is smooth.",
  "光临": "Welcome.",
  "光明": "The future is bright.",
  "光盘": "This is a CD.",
  "光荣": "This is a glorious event.",
  "广场": "The square is big.",
  "广大": "China has vast land.",
  "广泛": "This book has a wide readership.",
  "规矩": "He's well-behaved.",
  "规律": "Life should have regularity.",
  "规模": "The company is large in scale.",
  "规则": "Please follow the rules.",
  "柜台": "Please pay at the counter.",
  "滚": "The ball rolled down.",
  "锅": "I cook with a pot.",
  "国籍": "My nationality is Korean.",
  "国庆节": "National Day is a holiday.",
  "果实": "There's fruit on the tree.",
  "过分": "This is too much.",
  "过敏": "I'm allergic to pollen.",
  "过期": "The milk is expired.",
  "哈": "Haha, that's funny.",
  "海关": "I'm in line at customs.",
  "海鲜": "I like seafood.",
  "喊": "He shouted loudly.",
  "豪华": "This is a luxury hotel.",
  "好奇": "Children are curious.",
  "合法": "This is legal.",
  "合理": "The price is reasonable.",
  "合同": "Please sign the contract.",
  "合影": "Let's take a group photo.",
  "合作": "Let's cooperate.",
  "何必": "Why bother being so tired?",
  "何况": "I can't, let alone him.",
  "和平": "We want peace.",
  "核心": "This is the core issue.",
  "恨": "I hate him.",
  "横": "Please place horizontally.",
  "后果": "The consequences are serious.",
  "呼吸": "Please breathe deeply.",
  "忽视": "Please don't ignore.",
  "胡说": "Don't talk nonsense.",
  "胡同": "My home is in the alley.",
  "胡须": "He has a beard.",
  "壶": "This is a pot of tea.",
  "蝴蝶": "Butterflies are beautiful.",
  "糊涂": "He's really confused.",
  "花生": "I like peanuts.",
  "华裔": "He's of Chinese descent.",
  "滑冰": "I like to ice skate in winter.",
  "化学": "I study chemistry.",
  "划船": "Let's go rowing on the lake.",
  "话题": "Let's change the topic.",
  "怀念": "I miss my hometown.",
  "缓解": "Pressure has eased.",
  "幻想": "Stop fantasizing.",
  "慌张": "Don't panic.",
  "皇帝": "He is the emperor.",
  "皇后": "The empress is beautiful.",
  "黄瓜": "I like cucumbers.",
  "黄金": "Gold is expensive.",
  "灰": "The wall is gray.",
  "灰尘": "There's dust on the table.",
  "灰心": "Don't be discouraged.",
  "恢复": "I recovered my health.",
  "挥": "He waved goodbye.",
  "汇率": "The exchange rate changed.",
  "会计": "He's an accountant.",
  "婚礼": "I'm attending a wedding.",
  "婚姻": "Marriage is happy.",
  "活跃": "The atmosphere is lively.",
  "火柴": "I light fire with matches.",
  "伙伴": "He is my partner.",
  "机器": "This machine is expensive.",
  "肌肉": "He has well-developed muscles.",
  "基本": "Basically no problem.",
  "激烈": "The competition is fierce.",
  "及格": "I passed the exam.",
  "急忙": "He rushed out.",
  "集体": "We are a collective.",
  "集中": "Please concentrate.",
  "计算": "Please calculate the total.",
  "记录": "Please record it.",
  "记忆": "My memory is poor.",
  "纪录": "He broke the record.",
  "纪律": "Please follow discipline.",
  "纪念": "This is a souvenir.",
  "寂寞": "I feel lonely.",
  "夹子": "Please use the clip.",
  "家庭": "I have a happy family.",
  "家务": "I do housework.",
  "家乡": "I miss my hometown.",
  "嘉宾": "Welcome, distinguished guests.",
  "甲": "Team A won.",
  "假如": "If it rains, I won't go.",
  "假装": "He pretended not to see.",
  "价值": "This has value.",
  "驾驶": "He can drive a car.",
  "嫁": "She married him.",
  "尖锐": "This question is sharp.",
  "坚决": "I firmly oppose.",
  "坚强": "She is strong.",
  "肩膀": "His shoulders are broad.",
  "艰巨": "The task is daunting.",
  "艰苦": "Life is hard.",
  "煎": "I'm frying eggs.",
  "捡": "I picked up the wallet.",
  "剪刀": "Please give me scissors.",
  "简历": "Please send me your resume.",
  "简直": "This is just unbelievable.",
  "建立": "We established friendship.",
  "建设": "The country is building.",
  "建议": "I have a suggestion.",
  "建筑": "This is an old building.",
  "健身房": "I'm going to the gym to exercise.",
  "键盘": "The keyboard is broken.",
  "讲究": "He's particular.",
  "讲座": "I'm going to a lecture.",
  "降落": "The plane landed.",
  "酱油": "Please give me soy sauce.",
  "交换": "Let's exchange business cards.",
  "交际": "He has good social skills.",
  "郊区": "I live in the suburbs.",
  "浇": "Please water the flowers.",
  "胶水": "Please give me glue.",
  "角度": "Look from another angle.",
  "角色": "He plays the main role.",
  "狡猾": "The fox is cunning.",
  "教材": "This is a new textbook.",
  "教练": "He is a coach.",
  "教训": "I learned a lesson.",
  "阶段": "Now is a critical stage.",
  "接触": "I've been exposed to Chinese culture.",
  "接待": "She receives guests.",
  "接近": "We're close to the goal.",
  "接着": "Go on talking.",
  "节": "There are four classes today.",
  "节省": "I save time.",
  "结构": "This house has a good structure.",
  "结合": "Combine theory with practice.",
  "结论": "I reached a conclusion.",
  "结实": "This table is sturdy.",
  "结账": "Check, please.",
  "解放": "We were liberated.",
  "解说员": "The commentator explains well.",
  "戒烟": "He wants to quit smoking.",
  "戒指": "She's wearing a ring.",
  "届": "He's a third-class graduate.",
  "借口": "Don't make excuses.",
  "金属": "This is made of metal.",
  "尽力": "I'll do my best.",
  "尽量": "Please come as early as possible.",
  "紧": "The shoes are too tight.",
  "紧急": "This is an emergency.",
  "谨慎": "Please drive carefully.",
  "近代": "This is modern history.",
  "进步": "He has made great progress.",
  "进口": "This is an imported product.",
  "经典": "This is a classic.",
  "经营": "He runs a company.",
  "精力": "I'm full of energy.",
  "景色": "The scenery is beautiful.",
  "敬爱": "We respect our teachers.",
  "酒吧": "I'm going to the bar.",
  "救": "Please save me.",
  "救护车": "Call an ambulance.",
  "舅舅": "Uncle lives in Beijing.",
  "居然": "He unexpectedly didn't come.",
  "桔子": "Oranges are sweet.",
  "举": "Please raise your hand.",
  "巨大": "This is a huge change.",
  "具备": "He has the ability.",
  "具体": "Please be specific.",
  "俱乐部": "I joined a club.",
  "据说": "It's said he's leaving.",
  "聚会": "We have a gathering tonight.",
  "捐": "I donated money.",
  "卷": "Please roll it up.",
  "决赛": "There's a final tonight.",
  "决心": "I made up my mind.",
  "绝对": "I absolutely won't go.",
  "军事": "This is a military issue.",
  "均匀": "Please apply evenly.",
  "卡车": "The truck is big.",
  "开发": "We develop new products.",
  "开放": "The park is open.",
  "开幕式": "The opening ceremony was great.",
  "开心": "I'm happy.",
  "砍": "He's chopping trees.",
  "看不起": "Don't look down on people.",
  "看来": "It seems it'll rain.",
  "抗议": "They protest.",
  "烤鸭": "Beijing roast duck is famous.",
  "颗": "I ate a piece of candy.",
  "可见": "I can see you're working hard.",
  "可靠": "He is reliable.",
  "可怕": "This is so scary.",
  "克": "Please give me 500 grams.",
  "克服": "Overcome difficulties.",
  "刻苦": "He studies hard.",
  "客观": "Please look at it objectively.",
  "客厅": "The living room is big.",
  "课程": "The course is interesting.",
  "空间": "There's a lot of space here.",
  "空闲": "I read books in my free time.",
  "恐怖": "This is a horror movie.",
  "控制": "Please control your emotions.",
  "口味": "Do you like strong flavors?",
  "夸": "He praised me.",
  "矿泉水": "I drink mineral water.",
  "蜡烛": "The candle is lit.",
  "辣椒": "I can't eat chili peppers.",
  "来自": "I'm from Korea.",
  "拦": "Please don't stop me.",
  "烂": "The apple is rotten.",
  "狼": "Wolves are dangerous.",
  "劳动": "Labor is glorious.",
  "劳驾": "Excuse me, please move.",
  "老百姓": "I'm an ordinary citizen.",
  "老板": "He is my boss.",
  "老实": "He is honest.",
  "老鼠": "I'm afraid of mice.",
  "姥姥": "Grandma lives in the countryside.",
  "乐观": "She is optimistic.",
  "了不起": "You're amazing.",
  "雷": "There's thunder outside.",
  "类": "What kind is this?",
  "厘米": "Thirty centimeters.",
  "离婚": "They got divorced.",
  "梨": "Pears are sweet.",
  "礼拜天": "I rest on Sunday.",
  "理论": "Theory is important.",
  "理由": "What's your reason?",
  "力量": "He is very strong.",
  "立方": "This is cubic meters.",
  "立即": "Please leave immediately.",
  "立刻": "I'll come right away.",
  "利润": "The company's profit is high.",
  "利息": "The interest isn't small.",
  "利益": "For the common interest.",
  "利用": "Please use the time.",
  "粒": "A grain of rice.",
  "连忙": "He rushed over.",
  "连续剧": "I watch TV series.",
  "联合": "Let's unite.",
  "恋爱": "They are in love.",
  "良好": "I feel good.",
  "粮食": "Let's save food.",
  "临时": "This is a temporary arrangement.",
  "灵活": "He thinks flexibly.",
  "铃": "The bell rang.",
  "零件": "Parts are missing.",
  "零钱": "Please give me change.",
  "零食": "I like snacks.",
  "领导": "He is our leader.",
  "领域": "This is my field.",
  "浏览": "I browse the web.",
  "流传": "This story spread widely.",
  "龙": "The dragon is a Chinese symbol.",
  "漏": "The roof is leaking.",
  "陆地": "We reached land.",
  "陆续": "Guests arrived one after another.",
  "录取": "He was admitted to university.",
  "录音": "Please record.",
  "露": "There's dew on the grass.",
  "轮流": "We take turns on duty.",
  "论文": "I'm writing a thesis.",
  "逻辑": "He's logical.",
  "落后": "We can't fall behind.",
  "骂": "Mom scolded me.",
  "麦克风": "Please use the microphone.",
  "馒头": "I eat steamed buns.",
  "满足": "I'm satisfied.",
  "毛": "The cat's fur is soft.",
  "毛病": "The computer has a problem.",
  "矛盾": "They have a conflict.",
  "冒险": "This is too risky.",
  "贸易": "International trade.",
  "眉毛": "Her eyebrows are pretty.",
  "煤炭": "Coal factory.",
  "美术": "I study art.",
  "魅力": "She has charm.",
  "迷路": "I got lost.",
  "谜语": "I'm guessing a riddle.",
  "秘密": "This is a secret.",
  "秘书": "She is a secretary.",
  "密切": "Our relationship is close.",
  "蜜蜂": "Bees are flying.",
  "棉花": "Cotton is soft.",
  "面对": "I face the difficulty.",
  "面积": "The area is large.",
  "面临": "We face challenges.",
  "苗条": "She is slender.",
  "描写": "He describes vividly.",
  "秒": "Wait three seconds.",
  "民主": "Democracy is important.",
  "名牌": "She likes brand names.",
  "名片": "This is my business card.",
  "名胜": "This is a tourist attraction.",
  "明确": "Please explain clearly.",
  "明显": "This is obvious.",
  "明信片": "I'm sending a postcard.",
  "明星": "She is a big star.",
  "命令": "This is an order.",
  "命运": "Fate is in your own hands.",
  "摸": "Please don't touch.",
  "模仿": "He imitates stars.",
  "模糊": "The picture is blurry.",
  "摩托车": "He rides a motorcycle.",
  "陌生": "I'm unfamiliar here.",
  "某": "Someday I'll go.",
  "木头": "The table is made of wood.",
  "目标": "My goal is HSK 5.",
  "目录": "Please look at the table of contents.",
  "目前": "Currently no problems.",
  "哪怕": "Even if it rains, I'll go.",
  "难怪": "No wonder she's angry.",
  "难看": "This clothing is ugly.",
  "脑袋": "My head hurts.",
  "内科": "I'm seeing internal medicine.",
  "嫩": "The meat is tender.",
  "能干": "She is capable.",
  "能源": "Save energy.",
  "年代": "This is a 90s song.",
  "年纪": "She's not old.",
  "念": "Please read this paragraph.",
  "宁可": "I'd rather be alone.",
  "牛仔裤": "I wear jeans.",
  "农民": "He is a farmer.",
  "农业": "Agriculture is important.",
  "浓": "The tea is strong.",
  "女士": "Who is this lady?",
  "偶然": "I met him by chance.",
  "拍": "I took a picture.",
  "排队": "Please line up.",
  "排球": "I can play volleyball.",
  "派": "The company sent me on business.",
  "盼望": "I look forward to seeing you.",
  "培养": "Schools cultivate talent.",
  "赔偿": "You need to compensate.",
  "佩服": "I admire him.",
  "配合": "Please cooperate.",
  "盆": "This pot of flowers is pretty.",
  "碰见": "I met an old friend.",
  "批": "A batch of new products.",
  "批准": "The application was approved.",
  "披": "She's wearing a scarf.",
  "皮鞋": "He wears leather shoes.",
  "疲劳": "I'm very tired.",
  "匹": "A horse.",
  "片": "A slice of bread.",
  "片面": "This is a one-sided view.",
  "飘": "Snowflakes float down.",
  "频道": "Please change the channel.",
  "品种": "There are many varieties here.",
  "平": "The road is flat.",
  "平常": "I'm usually at home.",
  "平等": "We want equality.",
  "平方": "This house is 100 square meters.",
  "平衡": "Please maintain balance.",
  "平静": "My mood is calm.",
  "平均": "The average age is 30.",
  "评价": "Please evaluate.",
  "凭": "Entrance by ticket only.",
  "迫切": "I urgently need help.",
  "破产": "The company went bankrupt.",
  "破坏": "Please don't damage the environment.",
  "朴素": "She dresses simply.",
  "期待": "I look forward to meeting you.",
  "期间": "I was home during the break.",
  "其余": "The rest all left.",
  "奇迹": "This is a miracle.",
  "企图": "He tried to escape.",
  "企业": "He works at a big company.",
  "启发": "This inspires me.",
  "气氛": "The atmosphere is good.",
  "汽油": "Gasoline prices went up.",
  "牵": "I'm holding the child's hand.",
  "谦虚": "He is humble.",
  "签字": "Please sign.",
  "前途": "His future is bright.",
  "浅": "This river is shallow.",
  "欠": "I owe you money.",
  "枪": "Please put down the gun.",
  "强调": "He emphasized the key point.",
  "强烈": "I strongly oppose.",
  "抢": "He stole my wallet.",
  "悄悄": "He quietly left.",
  "瞧": "Look.",
  "巧妙": "His method is clever.",
  "切": "Please cut the apple.",
  "亲爱": "Dear, hello.",
  "亲切": "She is kind to people.",
  "亲自": "I'll go myself.",
  "侵略": "We oppose invasion.",
  "勤奋": "He is diligent.",
  "勤劳": "He works diligently.",
  "青": "The sky is azure.",
  "青春": "Youth is short.",
  "青少年": "He is a teenager.",
  "轻视": "Don't underestimate others.",
  "清淡": "I like light food.",
  "情景": "I can't forget that scene.",
  "情绪": "He is in a bad mood.",
  "请求": "I have a request.",
  "庆祝": "We celebrate birthdays.",
  "球迷": "He is a soccer fan.",
  "趋势": "This is a new trend.",
  "取消": "The meeting was canceled.",
  "娶": "He married her.",
  "去世": "His grandfather passed away.",
  "圈": "Please draw a circle.",
  "全面": "Comprehensive analysis.",
  "权力": "He has great power.",
  "权利": "This is my right.",
  "劝": "I advised him not to go.",
  "缺乏": "We lack experience.",
  "确定": "Please confirm the time.",
  "确认": "Please confirm the information.",
  "燃烧": "Fire is burning.",
  "嚷": "Please don't yell.",
  "绕": "I went around once.",
  "热爱": "I love life.",
  "热烈": "Warm welcome!",
  "热心": "She is enthusiastic.",
  "人才": "The company needs talent.",
  "人口": "China has a large population.",
  "人类": "Humans should protect the earth.",
  "人生": "Life is short.",
  "人事": "HR department.",
  "人物": "He is an important figure.",
  "人员": "There are many staff.",
  "忍不住": "I couldn't help laughing.",
  "日常": "Daily life.",
  "日程": "I arrange my schedule.",
  "日历": "Please look at the calendar.",
  "日期": "Please fill in the date.",
  "日用品": "I buy daily necessities.",
  "荣幸": "I'm honored.",
  "荣誉": "This is an honor.",
  "融化": "The snow melted.",
  "如何": "How do we solve this?",
  "如今": "Life is good now.",
  "软件": "Please install the software.",
  "弱": "He's weak.",
  "洒": "He spilled water.",
  "嗓子": "My throat hurts.",
  "杀": "He killed the bug.",
  "沙漠": "The desert is vast.",
  "沙滩": "Let's play at the beach.",
  "傻": "Don't be silly.",
  "晒": "I'm drying clothes.",
  "删除": "Please delete the file.",
  "闪电": "There's lightning outside.",
  "扇子": "Use a fan in summer.",
  "善良": "She is kind.",
  "善于": "He's good at communicating.",
  "商品": "This product is good.",
  "商业": "Commercial development.",
  "上当": "I got tricked.",
  "勺子": "Please give me a spoon.",
  "舌头": "I bit my tongue.",
  "蛇": "I'm afraid of snakes.",
  "舍不得": "I can't bear to leave.",
  "设备": "This is new equipment.",
  "设计": "He designed the house.",
  "设施": "Public facilities.",
  "射击": "He practices shooting.",
  "摄影": "I like photography.",
  "伸": "Please stretch out your hand.",
  "身材": "She has a good figure.",
  "身份": "Please show your ID.",
  "深刻": "Deep impression.",
  "神话": "This is a myth.",
  "神经": "He is on edge.",
  "神秘": "He is mysterious.",
  "升": "The sun has risen.",
  "生产": "The factory produces cars.",
  "生动": "He speaks vividly.",
  "声调": "Chinese has four tones.",
  "绳子": "Please give me a rope.",
  "省略": "Can be omitted.",
  "胜利": "We won.",
  "失眠": "I had insomnia last night.",
  "失去": "He lost the opportunity.",
  "失业": "He lost his job.",
  "诗": "I wrote a poem.",
  "石头": "There are stones on the road.",
  "时代": "This is a new era.",
  "时刻": "Please remember this moment.",
  "时髦": "She is fashionable.",
  "时期": "That was a difficult period.",
  "时尚": "This is fashion.",
  "实话": "Please tell the truth.",
  "实践": "Theory and practice.",
  "实习": "I'm interning at a hospital.",
  "实现": "I realized my dream.",
  "实行": "Implement new policy.",
  "实验": "I do experiments.",
  "实用": "This is practical.",
  "食物": "The food is delicious.",
  "使劲儿": "Please use force.",
  "始终": "He's been waiting all along.",
  "士兵": "He is a soldier.",
  "似的": "He's like a child.",
  "似乎": "It seems it'll rain.",
  "事实": "The fact is this.",
  "事物": "New things.",
  "事先": "Please notify in advance.",
  "试卷": "Please pass out the test.",
  "是否": "Do you agree or not?",
  "收获": "I have gains.",
  "收据": "Please give me the receipt.",
  "手工": "This is handmade.",
  "手术": "He's having surgery.",
  "手套": "Wear gloves.",
  "手续": "Process the procedures.",
  "手指": "My finger hurts.",
  "寿命": "His lifespan is long.",
  "受伤": "He got hurt.",
  "书架": "There are many books on the bookshelf.",
  "梳子": "Please give me a comb.",
  "舒适": "The bed is comfortable.",
  "输入": "Please enter the password.",
  "蔬菜": "I like vegetables.",
  "熟练": "He types proficiently.",
  "属于": "This belongs to me.",
  "鼠标": "The mouse is broken.",
  "数据": "Data is important.",
  "数码": "This is a digital camera.",
  "摔": "I fell once.",
  "甩": "He dumped me.",
  "双方": "Both sides agree.",
  "税": "I paid the tax.",
  "说不定": "Maybe he'll come.",
  "说服": "I persuaded him.",
  "丝绸": "This is made of silk.",
  "丝毫": "I don't know at all.",
  "私人": "This is a personal item.",
  "思考": "Please think.",
  "思想": "His thinking is open.",
  "撕": "Please don't tear the book.",
  "寺庙": "We're visiting the temple.",
  "宿舍": "I live in the dorm.",
  "随时": "You can come anytime.",
  "碎": "The cup is broken.",
  "损失": "The company's losses are big.",
  "缩短": "Please shorten the time.",
  "缩小": "Please narrow the scope.",
  "所": "I have some understanding.",
  "所谓": "So-called friends are like this.",
  "锁": "Please lock the door.",
  "塔": "This tower is tall.",
  "台阶": "Watch the steps.",
  "太极拳": "He practices tai chi.",
  "太太": "This is my wife.",
  "谈判": "We're negotiating.",
  "坦率": "He is frank.",
  "烫": "The soup is hot.",
  "逃": "He ran away.",
  "逃避": "Don't avoid the problem.",
  "桃": "I like peaches.",
  "套": "A set of clothes.",
  "特殊": "This is a special situation.",
  "特意": "I came specially to see you.",
  "特征": "This is its feature.",
  "疼爱": "She loves the child dearly.",
  "提": "He made a suggestion.",
  "提倡": "We advocate saving.",
  "提纲": "Please write an outline.",
  "提问": "Please ask questions.",
  "题目": "This is the exam question.",
  "体会": "I understood.",
  "体积": "The volume is large.",
  "体贴": "He is considerate.",
  "体现": "This embodies the spirit.",
  "体验": "I experienced life.",
  "天空": "The sky is blue.",
  "天真": "The child is innocent.",
  "田野": "The fields are beautiful.",
  "挑战": "I like challenges.",
  "通常": "I usually get up at 7.",
  "通讯": "Communication is convenient.",
  "同时": "He's learning two languages at the same time.",
  "铜": "This is made of copper.",
  "统一": "Opinions are unified.",
  "统治": "He ruled the country.",
  "痛苦": "He's in pain.",
  "痛快": "We had a great time.",
  "投资": "He invests in stocks.",
  "透明": "Glass is transparent.",
  "突出": "His grades are outstanding.",
  "土地": "This land is vast.",
  "土豆": "I like potatoes.",
  "吐": "I feel nauseous.",
  "兔子": "Rabbits are cute.",
  "团": "I joined a group.",
  "推辞": "He declined.",
  "推广": "Please promote this method.",
  "推荐": "I recommend this book.",
  "退": "Please step back.",
  "退步": "He regressed.",
  "退休": "My father retired.",
  "歪": "The picture hangs crooked.",
  "外交": "He works in diplomacy.",
  "弯": "It curves ahead.",
  "完美": "This is perfect.",
  "完善": "The system needs improvement.",
  "完整": "This book set is complete.",
  "玩具": "Children like toys.",
  "万一": "What if it rains?",
  "王子": "He's like a prince.",
  "往返": "I commute every day.",
  "危害": "Smoking harms health.",
  "威胁": "Please don't threaten me.",
  "微笑": "She's smiling.",
  "围巾": "She's wearing a scarf.",
  "围绕": "We discuss around this issue.",
  "违反": "Please don't violate the rules.",
  "唯一": "This is the only way.",
  "维护": "We uphold justice.",
  "伟大": "He is a great person.",
  "尾巴": "The dog's tail is wagging.",
  "委屈": "I feel wronged.",
  "委托": "I entrusted him with the matter.",
  "卫生间": "Where's the bathroom?",
  "未必": "It may not be true.",
  "未来": "The future is bright.",
  "位置": "Please sit in this position.",
  "胃": "My stomach hurts.",
  "温暖": "The room is warm.",
  "温柔": "She is gentle.",
  "文件": "Please send me the document.",
  "文具": "I'm buying stationery.",
  "文明": "Chinese civilization is ancient.",
  "文学": "I like literature.",
  "闻": "I smelled fragrance.",
  "吻": "She kissed the child.",
  "稳定": "The situation has stabilized.",
  "问候": "Please give him my regards.",
  "卧室": "The bedroom is quiet.",
  "屋子": "The room is big.",
  "无奈": "I'm helpless.",
  "无数": "There are countless stars in the sky.",
  "武器": "Please put down your weapon.",
  "武术": "I study martial arts.",
  "物理": "I study physics.",
  "物质": "Material life is rich.",
  "雾": "There's fog today.",
  "吸收": "Trees absorb water.",
  "戏剧": "I like theater.",
  "系": "Please fasten your seatbelt.",
  "系领带": "He's tying a tie.",
  "系统": "This is a new system.",
  "细节": "Pay attention to details.",
  "瞎": "Don't talk nonsense.",
  "下载": "Please download the file.",
  "吓": "You scared me.",
  "鲜艳": "The flowers are vibrant.",
  "显得": "She looks young.",
  "显然": "Clearly he doesn't know.",
  "显示": "The monitor is broken.",
  "县": "I'm going to that county.",
  "现金": "I'll pay in cash.",
  "现实": "Face reality.",
  "现象": "This is a common phenomenon.",
  "相处": "We get along well.",
  "相当": "He is quite smart.",
  "相对": "This is relative.",
  "相关": "This is related to you.",
  "相似": "They are similar.",
  "享受": "Enjoy life.",
  "想念": "I miss my family.",
  "想象": "Please imagine.",
  "项": "This is a new project.",
  "项链": "She wears a necklace.",
  "项目": "We're working on a project.",
  "象棋": "I can play Chinese chess.",
  "象征": "This symbolizes friendship.",
  "橡皮": "Please give me an eraser.",
  "消费": "He spends a lot.",
  "消化": "My digestion is poor.",
  "消灭": "Eliminate pests.",
  "消失": "He disappeared.",
  "销售": "He does sales.",
  "小吃": "I like snacks.",
  "小伙子": "This young man is smart.",
  "小麦": "This field is wheat.",
  "小气": "He is stingy.",
  "小偷": "Watch out for thieves.",
  "孝顺": "She is filial.",
  "效率": "Work efficiency is high.",
  "歇": "Let's rest for a moment.",
  "协调": "The colors are coordinated.",
  "斜": "The picture on the wall is slanted.",
  "心理": "Mental health is important.",
  "心脏": "The heart is beating fast.",
  "欣赏": "I admire her.",
  "信封": "Please give me an envelope.",
  "信号": "The signal is poor.",
  "信息": "Please send the information.",
  "行动": "Please act immediately.",
  "行人": "Pedestrians, please use the sidewalk.",
  "行为": "His behavior is bad.",
  "行业": "This industry is hard.",
  "形成": "A habit has formed.",
  "形容": "Indescribable.",
  "形式": "This format is good.",
  "形势": "The situation is grave.",
  "形象": "His image is good.",
  "形状": "What shape is this?",
  "幸亏": "Luckily you helped me.",
  "幸运": "I'm lucky.",
  "性质": "What's the nature of this?",
  "兄弟": "They are brothers.",
  "胸": "His chest is broad.",
  "雄伟": "The Great Wall is majestic.",
  "休闲": "I like leisure time.",
  "修改": "Please revise the article.",
  "虚心": "Please learn with humility.",
  "叙述": "Please describe what happened.",
  "宣布": "Please announce the results.",
  "宣传": "We promote products.",
  "选举": "We elect a class president.",
  "学期": "The new semester started.",
  "学术": "Academic research.",
  "学问": "He has deep learning.",
  "寻找": "I'm searching.",
  "询问": "Please inquire in detail.",
  "迅速": "Please act quickly.",
  "训练": "I train new employees.",
  "延长": "The time was extended.",
  "严肃": "He is serious.",
  "宴会": "There's a banquet tonight.",
  "阳台": "There are flowers on the balcony.",
  "痒": "I'm itchy.",
  "样式": "This is a new style.",
  "腰": "My back hurts.",
  "摇": "She shakes her head.",
  "咬": "The dog bit me.",
  "要不": "Or shall we eat?",
  "要是": "If I have time, I'll go.",
  "业务": "I handle business.",
  "业余": "I paint in my spare time.",
  "夜": "The night is dark.",
  "液体": "Water is liquid.",
  "一辈子": "We're friends for life.",
  "一旦": "Once decided, no change.",
  "一路": "Have a safe trip.",
  "一致": "Our opinions are consistent.",
  "依然": "He's still waiting.",
  "移动": "Please move this.",
  "移民": "He immigrated to America.",
  "遗憾": "It's a pity.",
  "疑问": "I have doubts.",
  "乙": "Team B is also strong.",
  "以及": "Apples, bananas, and oranges.",
  "以来": "Since then.",
  "义务": "This is my duty.",
  "议论": "Everyone is discussing.",
  "意外": "This is unexpected.",
  "意义": "This has significant meaning.",
  "因而": "It rained, therefore I didn't go.",
  "因素": "This is a key factor.",
  "银": "This is silver.",
  "应付": "I can't cope.",
  "应聘": "I'm going for an interview.",
  "应用": "Please apply your knowledge.",
  "英俊": "He is handsome.",
  "英雄": "He is a hero.",
  "迎接": "I'm going to greet him.",
  "营养": "Please pay attention to nutrition.",
  "营业": "The shop is open.",
  "影子": "I saw a shadow.",
  "硬币": "I have a few coins.",
  "硬件": "The computer hardware is good.",
  "拥抱": "She hugged me.",
  "拥挤": "It's crowded here.",
  "勇气": "You need courage.",
  "用途": "What's the use of this?",
  "优惠": "This is a discount price.",
  "优美": "The music is elegant.",
  "优势": "We have an advantage.",
  "悠久": "The history is long.",
  "犹豫": "Don't hesitate.",
  "邮局": "I'm going to the post office to send a letter.",
  "油炸": "I like fried food.",
  "游览": "I toured Beijing.",
  "有利": "This is good for us.",
  "幼儿园": "The child goes to kindergarten.",
  "娱乐": "I like entertainment shows.",
  "与其": "Rather than wait, just go.",
  "宇宙": "The universe is mysterious.",
  "语气": "Her tone is gentle.",
  "玉米": "I like corn.",
  "预报": "Weather forecast.",
  "预订": "I booked a room.",
  "预防": "Please prevent colds.",
  "元旦": "Happy New Year!",
  "原料": "This is the raw material.",
  "原则": "This is a matter of principle.",
  "缘故": "For some reason.",
  "愿望": "I have a wish.",
  "晕": "I get carsick.",
  "运气": "I have good luck.",
  "运输": "Transport, shipping.",
  "运用": "Please use your knowledge.",
  "灾害": "Natural disasters.",
  "再三": "I considered repeatedly.",
  "赞成": "I agree with you.",
  "赞美": "He praised her.",
  "糟糕": "Really terrible.",
  "造成": "This caused losses.",
  "则": "Gain then lose.",
  "责备": "Please don't blame me.",
  "摘": "I picked apples.",
  "粘贴": "Please paste the text.",
  "展开": "Please unfold the map.",
  "展览": "I'm going to see the exhibit.",
  "占线": "The phone is busy.",
  "战争": "The war ended.",
  "长途": "I'm making a long-distance call.",
  "涨": "Prices went up.",
  "掌握": "I mastered the skill.",
  "账户": "Please enter your account.",
  "招待": "Please entertain the guests.",
  "召开": "Convene a meeting.",
  "照常": "Please come to work as usual.",
  "哲学": "I study philosophy.",
  "着凉": "I caught a cold.",
  "针对": "Regarding this issue.",
  "珍惜": "Please cherish time.",
  "真理": "There is only one truth.",
  "真实": "This is a true story.",
  "诊断": "The doctor diagnosed me.",
  "枕头": "My pillow is soft.",
  "阵": "A gust of wind blew in.",
  "振动": "The phone vibrated.",
  "争论": "They argued.",
  "争取": "Strive for time.",
  "征求": "Seek opinions.",
  "挣钱": "He doesn't earn much money.",
  "睁": "Please open your eyes.",
  "整个": "The whole room is clean.",
  "整体": "Look at the overall effect.",
  "正": "He is sleeping.",
  "证件": "Please show your ID.",
  "证据": "I have evidence.",
  "政策": "New policy.",
  "政府": "The government announced.",
  "政治": "I'm not interested in politics.",
  "支": "I have a pen.",
  "支票": "Please pay by check.",
  "执行": "Please execute the order.",
  "执照": "Please show your license.",
  "直": "Please go straight.",
  "指导": "Please guide me.",
  "指挥": "He conducts the orchestra.",
  "至今": "I remember to this day.",
  "至于": "As for him, I don't know.",
  "制定": "We make plans.",
  "制度": "The company rules are strict.",
  "制作": "He makes cake.",
  "治疗": "I'm receiving treatment.",
  "秩序": "Please maintain order.",
  "智慧": "He is wise.",
  "中介": "I found a broker.",
  "中心": "Downtown is lively.",
  "中旬": "Mid-May.",
  "钟": "Please look at the clock.",
  "重": "This bag is heavy.",
  "重复": "Please don't repeat.",
  "重量": "How much does it weigh?",
  "周到": "The service is thoughtful.",
  "竹子": "The bamboo is tall.",
  "逐步": "We improve gradually.",
  "主持": "She hosts the show.",
  "主观": "This is too subjective.",
  "主人": "I'm the owner here.",
  "主席": "He is the chairman.",
  "主张": "I advocate for peace.",
  "煮": "I boil rice.",
  "嘱咐": "Mom told me to.",
  "注册": "Please register an account.",
  "祝福": "Bless you.",
  "抓紧": "Please hurry up.",
  "专家": "He is an expert.",
  "专心": "Please focus on studies.",
  "转变": "His attitude changed.",
  "转告": "Please tell him.",
  "装": "Please pack well.",
  "装饰": "The room decoration is pretty.",
  "状况": "The status is good.",
  "状态": "I'm in good shape.",
  "追求": "Pursue dreams.",
  "咨询": "I consulted the doctor.",
  "姿势": "Please maintain the posture.",
  "资格": "He's qualified.",
  "资金": "Funds aren't enough.",
  "资料": "Please prepare the materials.",
  "资源": "Save resources.",
  "紫": "I like purple.",
  "字幕": "Please turn on subtitles.",
  "自从": "Since coming to China.",
  "自动": "The door opened automatically.",
  "自豪": "I feel proud.",
  "自觉": "Please be self-disciplined.",
  "自私": "He is selfish.",
  "自信": "She is confident.",
  "自由": "I like freedom.",
  "自愿": "I volunteered to participate.",
  "宗教": "I study religion.",
  "综合": "Please consider comprehensively.",
  "总裁": "He is the CEO.",
  "总共": "100 yuan in total.",
  "总理": "He is the premier.",
  "总算": "Finally arrived.",
  "总统": "He is the president.",
  "总之": "Anyway, it's over.",
  "阻止": "Please stop him.",
  "组合": "This is a new combination.",
  "祖国": "I love my homeland.",
  "祖先": "Our ancestors.",
  "最初": "At first I didn't like it.",
  "罪犯": "The police caught the criminal.",
  "醉": "He's drunk.",
  "尊敬": "I respect my teachers.",
  "遵守": "Please follow the rules.",
  "作品": "This is his work.",
  "作为": "As a teacher, I must be responsible.",
  "作文": "I'm writing an essay."
};
